language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install codecov flake8 pytest pytest-cov

script: 
  - python -m pytest -v -s --cov=factorial *.py
  - flake8 *.py

after_success:
  - codecov
